@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM 


"C:\Program Files\IAR Systems\Embedded Workbench 6.0_0\common\bin\cspybat" "C:\Program Files\IAR Systems\Embedded Workbench 6.0_0\avr\bin\avrproc.dll" "C:\Program Files\IAR Systems\Embedded Workbench 6.0_0\avr\bin\avrJtagIce3.dll"  %1 --plugin "C:\Program Files\IAR Systems\Embedded Workbench 6.0_0\avr\bin\avrlibsupportbat.dll" --backend -B "--cpu=xm32a4u" "--enhanced_core" "-p" "C:\Program Files\IAR Systems\Embedded Workbench 6.0_0\avr\Config\ioxm32a4u.ddf" "--eeprom_size" "1024" "-d" "jtagIce3" "--avrone_jtag_clock=100000" "--drv_communication=USB" "--drv_debug_port=pdi" 


